var classes = [
    {
        "name": "Ru",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "pluralize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 55,
        "vocabulary": 26,
        "volume": 258.52,
        "difficulty": 12.47,
        "effort": 3222.93,
        "level": 0.08,
        "bugs": 0.09,
        "time": 179,
        "intelligentContent": 20.74,
        "number_operators": 21,
        "number_operands": 34,
        "number_operators_unique": 11,
        "number_operands_unique": 15,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 54.27,
        "mIwoC": 54.27,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "app\\models\\Utils",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "dateBelongsToRange",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "DateTime",
            "DateTime",
            "DateTime",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 26,
        "vocabulary": 12,
        "volume": 93.21,
        "difficulty": 8,
        "effort": 745.67,
        "level": 0.13,
        "bugs": 0.03,
        "time": 41,
        "intelligentContent": 11.65,
        "number_operators": 10,
        "number_operands": 16,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 57.16,
        "mIwoC": 57.16,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "app\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "KsUtils\\File\\Filter\\Extension",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setExtension",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMatcher",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "KsUtils\\File\\Filter"
        ],
        "parents": [],
        "lcom": 1,
        "length": 32,
        "vocabulary": 15,
        "volume": 125.02,
        "difficulty": 7,
        "effort": 875.14,
        "level": 0.14,
        "bugs": 0.04,
        "time": 49,
        "intelligentContent": 17.86,
        "number_operators": 11,
        "number_operands": 21,
        "number_operators_unique": 6,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 22,
        "lloc": 22,
        "mi": 55.9,
        "mIwoC": 55.9,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "KsUtils\\File\\Filter\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "KsUtils\\File\\OperationException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "KsUtils\\File\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "KsUtils\\File\\ZipException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "KsUtils\\File\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "KsUtils\\File\\Dir",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "mkdirIfNotExists",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isReadableOrThrow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWritableOrThrow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "copy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllFiles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 21,
        "ccn": 15,
        "ccnMethodMax": 5,
        "externals": [
            "KsUtils\\File\\OperationException",
            "KsUtils\\File\\OperationException",
            "KsUtils\\File\\OperationException",
            "KsUtils\\File\\OperationException",
            "KsUtils\\File\\Filter"
        ],
        "parents": [],
        "lcom": 3,
        "length": 111,
        "vocabulary": 25,
        "volume": 515.47,
        "difficulty": 12.16,
        "effort": 6267.01,
        "level": 0.08,
        "bugs": 0.17,
        "time": 348,
        "intelligentContent": 42.4,
        "number_operators": 34,
        "number_operands": 77,
        "number_operators_unique": 6,
        "number_operands_unique": 19,
        "cloc": 0,
        "loc": 70,
        "lloc": 70,
        "mi": 38.74,
        "mIwoC": 38.74,
        "commentWeight": 0,
        "kanDefect": 1.42,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.07,
        "relativeSystemComplexity": 10.07,
        "totalStructuralComplexity": 63,
        "totalDataComplexity": 7.5,
        "totalSystemComplexity": 70.5,
        "package": "KsUtils\\File\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "KsUtils\\File\\Zip",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ensureZipResource",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unpackAllTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unpackZipFileItem",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getZipErrorMessage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "KsUtils\\File",
            "KsUtils\\File\\ZipException",
            "KsUtils\\File\\ZipException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 119,
        "vocabulary": 71,
        "volume": 731.82,
        "difficulty": 3.94,
        "effort": 2882.93,
        "level": 0.25,
        "bugs": 0.24,
        "time": 160,
        "intelligentContent": 185.77,
        "number_operators": 15,
        "number_operands": 104,
        "number_operators_unique": 5,
        "number_operands_unique": 66,
        "cloc": 0,
        "loc": 44,
        "lloc": 44,
        "mi": 43.42,
        "mIwoC": 43.42,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.48,
        "relativeSystemComplexity": 16.48,
        "totalStructuralComplexity": 80,
        "totalDataComplexity": 2.4,
        "totalSystemComplexity": 82.4,
        "package": "KsUtils\\File\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "KsPaginator",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotalPages",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCurPage",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getItemsOnPage",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPage1Url",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPageNUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUrlNplaceholder",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setTotalPages",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setCurPage",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setItemsOnPage",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUrl1",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setUrlN",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotalItems",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFrom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOffset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "init",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 17,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 6,
        "wmc": 26,
        "ccn": 10,
        "ccnMethodMax": 4,
        "externals": [
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 1,
        "length": 136,
        "vocabulary": 24,
        "volume": 623.55,
        "difficulty": 26.7,
        "effort": 16648.92,
        "level": 0.04,
        "bugs": 0.21,
        "time": 925,
        "intelligentContent": 23.35,
        "number_operators": 47,
        "number_operands": 89,
        "number_operators_unique": 9,
        "number_operands_unique": 15,
        "cloc": 0,
        "loc": 99,
        "lloc": 99,
        "mi": 35.55,
        "mIwoC": 35.55,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.4,
        "relativeSystemComplexity": 11.4,
        "totalStructuralComplexity": 153,
        "totalDataComplexity": 40.75,
        "totalSystemComplexity": 193.75,
        "package": "KsUtils\\File\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "createFromPeriod",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFullDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isMonday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isTuesday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWednesday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isThursday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFriday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSaturday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSunday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNameShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNamesShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNumList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMinDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMaxDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMaxDay",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isLeapYear",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPast",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFuture",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isCurrent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNameShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getYear",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonth",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 33,
        "nbMethods": 32,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 31,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 59,
        "ccn": 27,
        "ccnMethodMax": 5,
        "externals": [
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "InvalidArgumentException",
            "DateTime",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "self",
            "self"
        ],
        "parents": [],
        "lcom": 3,
        "length": 476,
        "vocabulary": 94,
        "volume": 3119.98,
        "difficulty": 28.7,
        "effort": 89543.55,
        "level": 0.03,
        "bugs": 1.04,
        "time": 4975,
        "intelligentContent": 108.71,
        "number_operators": 148,
        "number_operands": 328,
        "number_operators_unique": 14,
        "number_operands_unique": 80,
        "cloc": 153,
        "loc": 368,
        "lloc": 215,
        "mi": 63.07,
        "mIwoC": 21.02,
        "commentWeight": 42.04,
        "kanDefect": 1.06,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 2.87,
        "relativeSystemComplexity": 123.87,
        "totalStructuralComplexity": 3993,
        "totalDataComplexity": 94.83,
        "totalSystemComplexity": 4087.83,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "kfilin\\Calendar\\Period",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contains",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date",
            "self",
            "DateTime",
            "InvalidArgumentException",
            "DateTime",
            "InvalidArgumentException",
            "DateTime",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 3,
        "length": 50,
        "vocabulary": 16,
        "volume": 200,
        "difficulty": 7.05,
        "effort": 1409.09,
        "level": 0.14,
        "bugs": 0.07,
        "time": 78,
        "intelligentContent": 28.39,
        "number_operators": 19,
        "number_operands": 31,
        "number_operators_unique": 5,
        "number_operands_unique": 11,
        "cloc": 8,
        "loc": 50,
        "lloc": 42,
        "mi": 76.44,
        "mIwoC": 47.4,
        "commentWeight": 29.04,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 11,
        "totalSystemComplexity": 14,
        "package": "kfilin\\Calendar\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\ru\\Month",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayNamesShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Helpers\\Calendar\\Month"
        ],
        "parents": [
            "Helpers\\Calendar\\Month"
        ],
        "lcom": 3,
        "length": 55,
        "vocabulary": 39,
        "volume": 290.7,
        "difficulty": 0.68,
        "effort": 198.9,
        "level": 1.46,
        "bugs": 0.1,
        "time": 11,
        "intelligentContent": 424.87,
        "number_operators": 3,
        "number_operands": 52,
        "number_operators_unique": 1,
        "number_operands_unique": 38,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 56.35,
        "mIwoC": 56.35,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "package": "Helpers\\Calendar\\ru\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Generator\\Workdays",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "make",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWeekend",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "kfilin\\Calendar\\GeneratorIf",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 12,
        "volume": 118.3,
        "difficulty": 11,
        "effort": 1301.34,
        "level": 0.09,
        "bugs": 0.04,
        "time": 72,
        "intelligentContent": 10.75,
        "number_operators": 11,
        "number_operands": 22,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 14,
        "loc": 39,
        "lloc": 25,
        "mi": 94.48,
        "mIwoC": 54.45,
        "commentWeight": 40.03,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 25.44,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 76.33,
        "package": "Helpers\\Calendar\\Generator\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "kfilin\\Calendar\\Date",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsPhpObject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DateTime",
            "DateInterval",
            "DateTime",
            "DateInterval",
            "DateTime",
            "DateTime",
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date"
        ],
        "parents": [],
        "lcom": 5,
        "length": 76,
        "vocabulary": 17,
        "volume": 310.65,
        "difficulty": 5.79,
        "effort": 1797.32,
        "level": 0.17,
        "bugs": 0.1,
        "time": 100,
        "intelligentContent": 53.69,
        "number_operators": 22,
        "number_operands": 54,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 37,
        "loc": 84,
        "lloc": 47,
        "mi": 88.76,
        "mIwoC": 45.94,
        "commentWeight": 42.82,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.55,
        "relativeSystemComplexity": 17.55,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 12.4,
        "totalSystemComplexity": 140.4,
        "package": "kfilin\\Calendar\\",
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "TreeNodeEmpty",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addChild",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getChildren",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isRoot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setData",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "TreeNode",
            "TreeNode"
        ],
        "parents": [
            "TreeNode"
        ],
        "lcom": 9,
        "length": 24,
        "vocabulary": 7,
        "volume": 67.38,
        "difficulty": 2.6,
        "effort": 175.18,
        "level": 0.38,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 25.91,
        "number_operators": 11,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 42,
        "lloc": 42,
        "mi": 51.65,
        "mIwoC": 51.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6.22,
        "relativeSystemComplexity": 6.22,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 56,
        "totalSystemComplexity": 56,
        "package": "kfilin\\Calendar\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "TreeNode",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPid",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addChild",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getChildren",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setData",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasChildren",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasParent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 1,
        "wmc": 11,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "TreeNode"
        ],
        "parents": [],
        "lcom": 1,
        "length": 44,
        "vocabulary": 11,
        "volume": 152.21,
        "difficulty": 7.71,
        "effort": 1174.23,
        "level": 0.13,
        "bugs": 0.05,
        "time": 65,
        "intelligentContent": 19.73,
        "number_operators": 17,
        "number_operands": 27,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 53,
        "lloc": 53,
        "mi": 46.84,
        "mIwoC": 46.84,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.75,
        "relativeSystemComplexity": 4.75,
        "totalStructuralComplexity": 10,
        "totalDataComplexity": 37.5,
        "totalSystemComplexity": 47.5,
        "package": "kfilin\\Calendar\\",
        "pageRank": 0.76,
        "afferentCoupling": 5,
        "efferentCoupling": 2,
        "instability": 0.29,
        "violations": {}
    },
    {
        "name": "TreeFabric",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setIdField",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPidField",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setNameField",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 3,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "InvalidArgumentException",
            "Tree",
            "TreeNode"
        ],
        "parents": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 14,
        "volume": 152.29,
        "difficulty": 4.09,
        "effort": 623.02,
        "level": 0.24,
        "bugs": 0.05,
        "time": 35,
        "intelligentContent": 37.23,
        "number_operators": 10,
        "number_operands": 30,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 6,
        "loc": 43,
        "lloc": 37,
        "mi": 77.45,
        "mIwoC": 50.1,
        "commentWeight": 27.35,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.9,
        "relativeSystemComplexity": 1.9,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 9.5,
        "package": "kfilin\\Calendar\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Str",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "createRandomNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createRandom",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "limitChars",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "startsWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "endsWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "self"
        ],
        "parents": [],
        "lcom": 5,
        "length": 123,
        "vocabulary": 63,
        "volume": 735.21,
        "difficulty": 8.87,
        "effort": 6519.75,
        "level": 0.11,
        "bugs": 0.25,
        "time": 362,
        "intelligentContent": 82.91,
        "number_operators": 29,
        "number_operands": 94,
        "number_operators_unique": 10,
        "number_operands_unique": 53,
        "cloc": 36,
        "loc": 85,
        "lloc": 49,
        "mi": 84.41,
        "mIwoC": 42.12,
        "commentWeight": 42.29,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 25,
        "totalSystemComplexity": 30,
        "package": "Helpers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Dt\\Formatters\\Ru",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFull",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthShortList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthFullList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthFullGenList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthFullPropList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 6,
        "length": 102,
        "vocabulary": 60,
        "volume": 602.5,
        "difficulty": 0.83,
        "effort": 500.38,
        "level": 1.2,
        "bugs": 0.2,
        "time": 28,
        "intelligentContent": 725.46,
        "number_operators": 4,
        "number_operands": 98,
        "number_operators_unique": 1,
        "number_operands_unique": 59,
        "cloc": 0,
        "loc": 26,
        "lloc": 26,
        "mi": 49.53,
        "mIwoC": 49.53,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 26,
        "totalSystemComplexity": 26,
        "package": "Helpers\\Dt\\Formatters\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "KsUtils\\File",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "incrVersion",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isReadableOrThrow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDirFiles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 10,
        "ccnMethodMax": 6,
        "externals": [
            "KsUtils\\File\\OperationException",
            "KsUtils\\File\\OperationException"
        ],
        "parents": [],
        "lcom": 3,
        "length": 123,
        "vocabulary": 25,
        "volume": 571.19,
        "difficulty": 12.95,
        "effort": 7395.46,
        "level": 0.08,
        "bugs": 0.19,
        "time": 411,
        "intelligentContent": 44.12,
        "number_operators": 41,
        "number_operands": 82,
        "number_operators_unique": 6,
        "number_operands_unique": 19,
        "cloc": 9,
        "loc": 53,
        "lloc": 44,
        "mi": 73.3,
        "mIwoC": 43.5,
        "commentWeight": 29.8,
        "kanDefect": 0.87,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 8,
        "relativeSystemComplexity": 8,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 24,
        "totalSystemComplexity": 24,
        "package": "KsUtils\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Tree",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRoot",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "TreeNode",
            "TreeNode",
            "TreeNodeEmpty"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 8,
        "volume": 99,
        "difficulty": 7.2,
        "effort": 712.8,
        "level": 0.14,
        "bugs": 0.03,
        "time": 40,
        "intelligentContent": 13.75,
        "number_operators": 9,
        "number_operands": 24,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 22,
        "loc": 56,
        "lloc": 34,
        "mi": 93.49,
        "mIwoC": 52.22,
        "commentWeight": 41.27,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.49,
        "relativeSystemComplexity": 36.49,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 2.43,
        "totalSystemComplexity": 182.43,
        "package": "KsUtils\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "FilenameChanger",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cyr2lat",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toLower",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "spaces2underscores",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stripPunctuation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stripBadChars",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "stripTrailingSpaces",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cutLongBasename",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addSuffix",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFilename",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 20,
        "ccn": 11,
        "ccnMethodMax": 7,
        "externals": [
            "Exception"
        ],
        "parents": [],
        "lcom": 1,
        "length": 239,
        "vocabulary": 120,
        "volume": 1650.75,
        "difficulty": 5.13,
        "effort": 8470.94,
        "level": 0.19,
        "bugs": 0.55,
        "time": 471,
        "intelligentContent": 321.68,
        "number_operators": 44,
        "number_operands": 195,
        "number_operators_unique": 6,
        "number_operands_unique": 114,
        "cloc": 1,
        "loc": 78,
        "lloc": 77,
        "mi": 43.56,
        "mIwoC": 34.84,
        "commentWeight": 8.73,
        "kanDefect": 0.73,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 9.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 95,
        "totalSystemComplexity": 95,
        "package": "KsUtils\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]