var classes = [
    {
        "name": "Helpers\\Str\\Ru",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Helpers\\Str\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Helpers\\Str\\Random",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "createNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "self"
        ],
        "parents": [],
        "lcom": 2,
        "length": 65,
        "vocabulary": 50,
        "volume": 366.85,
        "difficulty": 3.82,
        "effort": 1400.7,
        "level": 0.26,
        "bugs": 0.12,
        "time": 78,
        "intelligentContent": 96.08,
        "number_operators": 9,
        "number_operands": 56,
        "number_operators_unique": 6,
        "number_operands_unique": 44,
        "cloc": 17,
        "loc": 36,
        "lloc": 19,
        "mi": 97.47,
        "mIwoC": 53.75,
        "commentWeight": 43.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 5.5,
        "package": "Helpers\\Str\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Str\\RuPluralizer",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fillRest",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isForm1",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isForm2",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 68,
        "vocabulary": 25,
        "volume": 315.78,
        "difficulty": 16.5,
        "effort": 5210.41,
        "level": 0.06,
        "bugs": 0.11,
        "time": 289,
        "intelligentContent": 19.14,
        "number_operators": 26,
        "number_operands": 42,
        "number_operators_unique": 11,
        "number_operands_unique": 14,
        "cloc": 25,
        "loc": 66,
        "lloc": 41,
        "mi": 87.15,
        "mIwoC": 46.38,
        "commentWeight": 40.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 10.5,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 7.5,
        "totalSystemComplexity": 52.5,
        "package": "Helpers\\Str\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getYear",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "is",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month\\Is",
            "Helpers\\Calendar\\Month\\Is",
            "Helpers\\Calendar\\Month\\Dt",
            "Helpers\\Calendar\\Month\\Dt"
        ],
        "parents": [],
        "lcom": 1,
        "length": 54,
        "vocabulary": 18,
        "volume": 225.18,
        "difficulty": 10.82,
        "effort": 2435.99,
        "level": 0.09,
        "bugs": 0.08,
        "time": 135,
        "intelligentContent": 20.81,
        "number_operators": 20,
        "number_operands": 34,
        "number_operators_unique": 7,
        "number_operands_unique": 11,
        "cloc": 38,
        "loc": 82,
        "lloc": 44,
        "mi": 90.22,
        "mIwoC": 46.74,
        "commentWeight": 43.49,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.78,
        "relativeSystemComplexity": 5.78,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 10.67,
        "totalSystemComplexity": 34.67,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.22,
        "afferentCoupling": 6,
        "efferentCoupling": 3,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "kfilin\\Calendar\\Period",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contains",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date",
            "kfilin\\Calendar\\Date",
            "self",
            "DateTime",
            "InvalidArgumentException",
            "DateTime",
            "InvalidArgumentException",
            "DateTime",
            "InvalidArgumentException"
        ],
        "parents": [],
        "lcom": 3,
        "length": 50,
        "vocabulary": 16,
        "volume": 200,
        "difficulty": 7.05,
        "effort": 1409.09,
        "level": 0.14,
        "bugs": 0.07,
        "time": 78,
        "intelligentContent": 28.39,
        "number_operators": 19,
        "number_operands": 31,
        "number_operators_unique": 5,
        "number_operands_unique": 11,
        "cloc": 8,
        "loc": 50,
        "lloc": 42,
        "mi": 76.44,
        "mIwoC": 47.4,
        "commentWeight": 29.04,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 3.67,
        "relativeSystemComplexity": 4.67,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 11,
        "totalSystemComplexity": 14,
        "package": "kfilin\\Calendar\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Dt",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsStr",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsObj",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "max",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "maxDay",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "min",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Year",
            "Helpers\\Calendar\\Month\\Fabric"
        ],
        "parents": [],
        "lcom": 1,
        "length": 84,
        "vocabulary": 36,
        "volume": 434.27,
        "difficulty": 9.43,
        "effort": 4094.58,
        "level": 0.11,
        "bugs": 0.14,
        "time": 227,
        "intelligentContent": 46.06,
        "number_operators": 18,
        "number_operands": 66,
        "number_operators_unique": 8,
        "number_operands_unique": 28,
        "cloc": 38,
        "loc": 78,
        "lloc": 40,
        "mi": 90.04,
        "mIwoC": 45.91,
        "commentWeight": 44.13,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.94,
        "relativeSystemComplexity": 36.94,
        "totalStructuralComplexity": 252,
        "totalDataComplexity": 6.57,
        "totalSystemComplexity": 258.57,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.14,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Formatter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 2,
        "length": 72,
        "vocabulary": 44,
        "volume": 393.08,
        "difficulty": 2.23,
        "effort": 877.24,
        "level": 0.45,
        "bugs": 0.13,
        "time": 49,
        "intelligentContent": 176.13,
        "number_operators": 11,
        "number_operands": 61,
        "number_operators_unique": 3,
        "number_operands_unique": 41,
        "cloc": 18,
        "loc": 43,
        "lloc": 25,
        "mi": 93.21,
        "mIwoC": 51.07,
        "commentWeight": 42.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 25.79,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 3.17,
        "totalSystemComplexity": 103.17,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.03,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Fabric",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "createFromPeriod",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "next",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 4,
        "length": 73,
        "vocabulary": 21,
        "volume": 320.64,
        "difficulty": 8.13,
        "effort": 2605.19,
        "level": 0.12,
        "bugs": 0.11,
        "time": 145,
        "intelligentContent": 39.46,
        "number_operators": 21,
        "number_operands": 52,
        "number_operators_unique": 5,
        "number_operands_unique": 16,
        "cloc": 24,
        "loc": 69,
        "lloc": 45,
        "mi": 85.3,
        "mIwoC": 45.72,
        "commentWeight": 39.59,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 6.67,
        "totalSystemComplexity": 22.67,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Is",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "currentYear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "current",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "past",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "future",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month\\Now",
            "Helpers\\Calendar\\Month\\Now",
            "Helpers\\Calendar\\Month\\Now",
            "Helpers\\Calendar\\Month\\Now",
            "Helpers\\Calendar\\Month\\Now",
            "Helpers\\Calendar\\Month\\Now"
        ],
        "parents": [],
        "lcom": 2,
        "length": 40,
        "vocabulary": 11,
        "volume": 138.38,
        "difficulty": 17.5,
        "effort": 2421.6,
        "level": 0.06,
        "bugs": 0.05,
        "time": 135,
        "intelligentContent": 7.91,
        "number_operators": 20,
        "number_operands": 20,
        "number_operators_unique": 7,
        "number_operands_unique": 4,
        "cloc": 25,
        "loc": 54,
        "lloc": 29,
        "mi": 95.77,
        "mIwoC": 52.3,
        "commentWeight": 43.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.84,
        "relativeSystemComplexity": 16.84,
        "totalStructuralComplexity": 80,
        "totalDataComplexity": 4.2,
        "totalSystemComplexity": 84.2,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.14,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\FormatterShort",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month\\Formatter",
            "Helpers\\Calendar\\Month\\Month"
        ],
        "parents": [
            "Helpers\\Calendar\\Month\\Formatter"
        ],
        "lcom": 2,
        "length": 37,
        "vocabulary": 25,
        "volume": 171.82,
        "difficulty": 2.05,
        "effort": 351.46,
        "level": 0.49,
        "bugs": 0.06,
        "time": 20,
        "intelligentContent": 84,
        "number_operators": 7,
        "number_operands": 30,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 13,
        "loc": 28,
        "lloc": 15,
        "mi": 101.94,
        "mIwoC": 58.43,
        "commentWeight": 43.51,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 9.63,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 19.25,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\ru\\Month",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayNamesShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Helpers\\Calendar\\Month"
        ],
        "parents": [
            "Helpers\\Calendar\\Month"
        ],
        "lcom": 3,
        "length": 55,
        "vocabulary": 39,
        "volume": 290.7,
        "difficulty": 0.68,
        "effort": 198.9,
        "level": 1.46,
        "bugs": 0.1,
        "time": 11,
        "intelligentContent": 424.87,
        "number_operators": 3,
        "number_operands": 52,
        "number_operators_unique": 1,
        "number_operands_unique": 38,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 56.35,
        "mIwoC": 56.35,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 9,
        "totalSystemComplexity": 9,
        "package": "Helpers\\Calendar\\ru\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Generator\\Workdays",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "make",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWeekend",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "kfilin\\Calendar\\GeneratorIf",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 12,
        "volume": 118.3,
        "difficulty": 11,
        "effort": 1301.34,
        "level": 0.09,
        "bugs": 0.04,
        "time": 72,
        "intelligentContent": 10.75,
        "number_operators": 11,
        "number_operands": 22,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 14,
        "loc": 39,
        "lloc": 25,
        "mi": 94.48,
        "mIwoC": 54.45,
        "commentWeight": 40.03,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 25.44,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 76.33,
        "package": "Helpers\\Calendar\\Generator\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Year",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "isLeap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 14,
        "volume": 95.18,
        "difficulty": 7,
        "effort": 666.29,
        "level": 0.14,
        "bugs": 0.03,
        "time": 37,
        "intelligentContent": 13.6,
        "number_operators": 11,
        "number_operands": 14,
        "number_operators_unique": 7,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 15,
        "lloc": 10,
        "mi": 102.92,
        "mIwoC": 63.93,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Week",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 7,
        "vocabulary": 7,
        "volume": 19.65,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 10,
        "loc": 21,
        "lloc": 11,
        "mi": 111.93,
        "mIwoC": 68.09,
        "commentWeight": 43.84,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Date",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsObj",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "now",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isMonday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isTuesday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWednesday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isThursday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFriday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSaturday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSanday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 16,
        "nbMethods": 16,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 16,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DateTime",
            "DateInterval",
            "DateTime",
            "DateInterval",
            "DateTime",
            "DateTime",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date"
        ],
        "parents": [],
        "lcom": 6,
        "length": 108,
        "vocabulary": 27,
        "volume": 513.53,
        "difficulty": 6.17,
        "effort": 3170.48,
        "level": 0.16,
        "bugs": 0.17,
        "time": 176,
        "intelligentContent": 83.18,
        "number_operators": 37,
        "number_operands": 71,
        "number_operators_unique": 4,
        "number_operands_unique": 23,
        "cloc": 69,
        "loc": 148,
        "lloc": 79,
        "mi": 83.05,
        "mIwoC": 39.49,
        "commentWeight": 43.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.56,
        "relativeSystemComplexity": 27.56,
        "totalStructuralComplexity": 400,
        "totalDataComplexity": 41,
        "totalSystemComplexity": 441,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.21,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "violations": {}
    },
    {
        "name": "Helpers\\Str",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "limitChars",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "startsWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "endsWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 3,
        "length": 58,
        "vocabulary": 21,
        "volume": 254.75,
        "difficulty": 11.69,
        "effort": 2978.67,
        "level": 0.09,
        "bugs": 0.08,
        "time": 165,
        "intelligentContent": 21.79,
        "number_operators": 20,
        "number_operands": 38,
        "number_operators_unique": 8,
        "number_operands_unique": 13,
        "cloc": 24,
        "loc": 58,
        "lloc": 34,
        "mi": 91.05,
        "mIwoC": 49.07,
        "commentWeight": 41.98,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 8.33,
        "relativeSystemComplexity": 8.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 25,
        "totalSystemComplexity": 25,
        "package": "Helpers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]