var classes = [
    {
        "name": "Helpers\\Str\\Ru",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Helpers\\Str\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Helpers\\Str\\Ru\\Pluralizer",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fillRest",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isForm1",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isForm2",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 68,
        "vocabulary": 25,
        "volume": 315.78,
        "difficulty": 16.5,
        "effort": 5210.41,
        "level": 0.06,
        "bugs": 0.11,
        "time": 289,
        "intelligentContent": 19.14,
        "number_operators": 26,
        "number_operands": 42,
        "number_operators_unique": 11,
        "number_operands_unique": 14,
        "cloc": 25,
        "loc": 66,
        "lloc": 41,
        "mi": 87.15,
        "mIwoC": 46.38,
        "commentWeight": 40.77,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 10.5,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 7.5,
        "totalSystemComplexity": 52.5,
        "package": "Helpers\\Str\\Ru\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Helpers\\Str\\Random",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "createNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "self"
        ],
        "parents": [],
        "lcom": 2,
        "length": 65,
        "vocabulary": 50,
        "volume": 366.85,
        "difficulty": 3.82,
        "effort": 1400.7,
        "level": 0.26,
        "bugs": 0.12,
        "time": 78,
        "intelligentContent": 96.08,
        "number_operators": 9,
        "number_operands": 56,
        "number_operators_unique": 6,
        "number_operands_unique": 44,
        "cloc": 17,
        "loc": 36,
        "lloc": 19,
        "mi": 97.47,
        "mIwoC": 53.75,
        "commentWeight": 43.73,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 5.5,
        "package": "Helpers\\Str\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getYear",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNumStr",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNum",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "is",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 7,
        "ccnMethodMax": 5,
        "externals": [
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month\\Is",
            "Helpers\\Calendar\\Month\\Is",
            "Helpers\\Calendar\\Month\\Dt",
            "Helpers\\Calendar\\Month\\Dt"
        ],
        "parents": [],
        "lcom": 1,
        "length": 56,
        "vocabulary": 18,
        "volume": 233.52,
        "difficulty": 11.14,
        "effort": 2600.52,
        "level": 0.09,
        "bugs": 0.08,
        "time": 144,
        "intelligentContent": 20.97,
        "number_operators": 21,
        "number_operands": 35,
        "number_operators_unique": 7,
        "number_operands_unique": 11,
        "cloc": 49,
        "loc": 97,
        "lloc": 48,
        "mi": 90.39,
        "mIwoC": 45.8,
        "commentWeight": 44.58,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.1,
        "relativeSystemComplexity": 6.1,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 14.67,
        "totalSystemComplexity": 42.67,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.19,
        "afferentCoupling": 7,
        "efferentCoupling": 3,
        "instability": 0.3,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Period",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contains",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isUnclosed",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "length",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "daysBetween",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDt1",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDt2",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDtList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 10,
        "ccnMethodMax": 5,
        "externals": [
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "self",
            "Helpers\\Calendar\\Date",
            "self",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date"
        ],
        "parents": [],
        "lcom": 3,
        "length": 68,
        "vocabulary": 18,
        "volume": 283.55,
        "difficulty": 20,
        "effort": 5671.1,
        "level": 0.05,
        "bugs": 0.09,
        "time": 315,
        "intelligentContent": 14.18,
        "number_operators": 28,
        "number_operands": 40,
        "number_operators_unique": 9,
        "number_operands_unique": 9,
        "cloc": 55,
        "loc": 106,
        "lloc": 51,
        "mi": 89.15,
        "mIwoC": 44.23,
        "commentWeight": 44.92,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 2.66,
        "relativeSystemComplexity": 11.66,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 21.25,
        "totalSystemComplexity": 93.25,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Dt",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsStr",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsObj",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "max",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "maxDay",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "min",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Year",
            "Helpers\\Calendar\\Month\\Fabric"
        ],
        "parents": [],
        "lcom": 1,
        "length": 90,
        "vocabulary": 38,
        "volume": 472.31,
        "difficulty": 10.55,
        "effort": 4983.72,
        "level": 0.09,
        "bugs": 0.16,
        "time": 277,
        "intelligentContent": 44.76,
        "number_operators": 22,
        "number_operands": 68,
        "number_operators_unique": 9,
        "number_operands_unique": 29,
        "cloc": 39,
        "loc": 79,
        "lloc": 40,
        "mi": 89.95,
        "mIwoC": 45.66,
        "commentWeight": 44.3,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 1.1,
        "relativeSystemComplexity": 26.1,
        "totalStructuralComplexity": 175,
        "totalDataComplexity": 7.67,
        "totalSystemComplexity": 182.67,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.11,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Ru\\Formatter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getMonthNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Helpers\\Calendar\\Month\\Formatter"
        ],
        "parents": [
            "Helpers\\Calendar\\Month\\Formatter"
        ],
        "lcom": 2,
        "length": 40,
        "vocabulary": 32,
        "volume": 200,
        "difficulty": 0.61,
        "effort": 122.58,
        "level": 1.63,
        "bugs": 0.07,
        "time": 7,
        "intelligentContent": 326.32,
        "number_operators": 2,
        "number_operands": 38,
        "number_operators_unique": 1,
        "number_operands_unique": 31,
        "cloc": 12,
        "loc": 24,
        "lloc": 12,
        "mi": 104.67,
        "mIwoC": 60.21,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "package": "Helpers\\Calendar\\Month\\Ru\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Ru\\FormatterShort",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month\\Ru\\Formatter",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [
            "Helpers\\Calendar\\Month\\Ru\\Formatter"
        ],
        "lcom": 2,
        "length": 37,
        "vocabulary": 25,
        "volume": 171.82,
        "difficulty": 2.05,
        "effort": 351.46,
        "level": 0.49,
        "bugs": 0.06,
        "time": 20,
        "intelligentContent": 84,
        "number_operators": 7,
        "number_operands": 30,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 10,
        "loc": 25,
        "lloc": 15,
        "mi": 99.94,
        "mIwoC": 58.43,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 9.63,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 19.25,
        "package": "Helpers\\Calendar\\Month\\Ru\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Formatter",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 2,
        "length": 72,
        "vocabulary": 44,
        "volume": 393.08,
        "difficulty": 2.23,
        "effort": 877.24,
        "level": 0.45,
        "bugs": 0.13,
        "time": 49,
        "intelligentContent": 176.13,
        "number_operators": 11,
        "number_operands": 61,
        "number_operators_unique": 3,
        "number_operands_unique": 41,
        "cloc": 23,
        "loc": 48,
        "lloc": 25,
        "mi": 94.99,
        "mIwoC": 51.07,
        "commentWeight": 43.92,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.59,
        "relativeSystemComplexity": 49.59,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 2.38,
        "totalSystemComplexity": 198.38,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Fabric",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "createFromPeriod",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFromDt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "InvalidArgumentException",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 4,
        "length": 73,
        "vocabulary": 21,
        "volume": 320.64,
        "difficulty": 8.13,
        "effort": 2605.19,
        "level": 0.12,
        "bugs": 0.11,
        "time": 145,
        "intelligentContent": 39.46,
        "number_operators": 21,
        "number_operands": 52,
        "number_operators_unique": 5,
        "number_operands_unique": 16,
        "cloc": 25,
        "loc": 70,
        "lloc": 45,
        "mi": 85.67,
        "mIwoC": 45.72,
        "commentWeight": 39.96,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 6.67,
        "totalSystemComplexity": 22.67,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\Is",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "currentYear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "current",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "past",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "future",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Helpers\\Calendar\\Month",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date",
            "Helpers\\Calendar\\Date"
        ],
        "parents": [],
        "lcom": 1,
        "length": 60,
        "vocabulary": 14,
        "volume": 228.44,
        "difficulty": 18,
        "effort": 4111.94,
        "level": 0.06,
        "bugs": 0.08,
        "time": 228,
        "intelligentContent": 12.69,
        "number_operators": 24,
        "number_operands": 36,
        "number_operators_unique": 7,
        "number_operands_unique": 7,
        "cloc": 24,
        "loc": 57,
        "lloc": 33,
        "mi": 91.77,
        "mIwoC": 49.55,
        "commentWeight": 42.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.7,
        "relativeSystemComplexity": 25.7,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 128.5,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.11,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Month\\FormatterShort",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getWeekdayNames",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Helpers\\Calendar\\Month\\Formatter",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [
            "Helpers\\Calendar\\Month\\Formatter"
        ],
        "lcom": 2,
        "length": 37,
        "vocabulary": 25,
        "volume": 171.82,
        "difficulty": 2.05,
        "effort": 351.46,
        "level": 0.49,
        "bugs": 0.06,
        "time": 20,
        "intelligentContent": 84,
        "number_operators": 7,
        "number_operands": 30,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 10,
        "loc": 25,
        "lloc": 15,
        "mi": 99.94,
        "mIwoC": 58.43,
        "commentWeight": 41.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 9.63,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.25,
        "totalSystemComplexity": 19.25,
        "package": "Helpers\\Calendar\\Month\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Generator\\Workdays",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "make",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWeekend",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "Helpers\\Calendar\\GeneratorIf",
            "Helpers\\Calendar\\Month"
        ],
        "parents": [],
        "lcom": 1,
        "length": 33,
        "vocabulary": 12,
        "volume": 118.3,
        "difficulty": 11,
        "effort": 1301.34,
        "level": 0.09,
        "bugs": 0.04,
        "time": 72,
        "intelligentContent": 10.75,
        "number_operators": 11,
        "number_operands": 22,
        "number_operators_unique": 6,
        "number_operands_unique": 6,
        "cloc": 13,
        "loc": 38,
        "lloc": 25,
        "mi": 93.81,
        "mIwoC": 54.45,
        "commentWeight": 39.36,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 25.44,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 76.33,
        "package": "Helpers\\Calendar\\Generator\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Year",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "isLeap",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 25,
        "vocabulary": 14,
        "volume": 95.18,
        "difficulty": 7,
        "effort": 666.29,
        "level": 0.14,
        "bugs": 0.03,
        "time": 37,
        "intelligentContent": 13.6,
        "number_operators": 11,
        "number_operands": 14,
        "number_operators_unique": 7,
        "number_operands_unique": 7,
        "cloc": 5,
        "loc": 15,
        "lloc": 10,
        "mi": 102.92,
        "mIwoC": 63.93,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Week",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 7,
        "vocabulary": 7,
        "volume": 19.65,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 7,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 10,
        "loc": 21,
        "lloc": 11,
        "mi": 111.93,
        "mIwoC": 68.09,
        "commentWeight": 43.84,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Helpers\\Calendar\\Date",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWeekdayNum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPrev",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNext",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAsArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isMonday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isTuesday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isWednesday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isThursday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFriday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSaturday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isSunday",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 13,
        "nbMethods": 13,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 13,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "DateTime",
            "parent",
            "Helpers\\Calendar\\Date",
            "DateInterval",
            "Helpers\\Calendar\\Date",
            "DateInterval"
        ],
        "parents": [
            "DateTime"
        ],
        "lcom": 4,
        "length": 72,
        "vocabulary": 24,
        "volume": 330.12,
        "difficulty": 4.7,
        "effort": 1551.55,
        "level": 0.21,
        "bugs": 0.11,
        "time": 86,
        "intelligentContent": 70.24,
        "number_operators": 25,
        "number_operands": 47,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 57,
        "loc": 117,
        "lloc": 60,
        "mi": 87.57,
        "mIwoC": 43.44,
        "commentWeight": 44.13,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 2.05,
        "relativeSystemComplexity": 27.05,
        "totalStructuralComplexity": 325,
        "totalDataComplexity": 26.67,
        "totalSystemComplexity": 351.67,
        "package": "Helpers\\Calendar\\",
        "pageRank": 0.32,
        "afferentCoupling": 5,
        "efferentCoupling": 5,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Helpers\\Str",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "limitChars",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "startsWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "endsWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [],
        "parents": [],
        "lcom": 3,
        "length": 58,
        "vocabulary": 21,
        "volume": 254.75,
        "difficulty": 11.69,
        "effort": 2978.67,
        "level": 0.09,
        "bugs": 0.08,
        "time": 165,
        "intelligentContent": 21.79,
        "number_operators": 20,
        "number_operands": 38,
        "number_operators_unique": 8,
        "number_operands_unique": 13,
        "cloc": 24,
        "loc": 58,
        "lloc": 34,
        "mi": 91.05,
        "mIwoC": 49.07,
        "commentWeight": 41.98,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 8.33,
        "relativeSystemComplexity": 8.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 25,
        "totalSystemComplexity": 25,
        "package": "Helpers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    }
]